# Generated by Django 4.2.7 on 2025-12-23 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nume')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sportiv',
                'verbose_name_plural': 'Sportivi',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nume antrenament')),
                ('frequency', models.CharField(choices=[('once', 'O singură dată'), ('weekly', 'Săptămânal')], max_length=10, verbose_name='Frecvență')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('weekday', models.IntegerField(blank=True, choices=[(0, 'Luni'), (1, 'Marți'), (2, 'Miercuri'), (3, 'Joi'), (4, 'Vineri'), (5, 'Sâmbătă'), (6, 'Duminică')], null=True, verbose_name='Ziua săptămânii')),
                ('start_time', models.TimeField(verbose_name='Ora de început')),
                ('end_time', models.TimeField(verbose_name='Ora de sfârșit')),
                ('active', models.BooleanField(default=True, verbose_name='Activ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sesiune de antrenament',
                'verbose_name_plural': 'Sesiuni de antrenament',
                'ordering': ['weekday', 'date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Ora check-in')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='gym.athlete', verbose_name='Sportiv')),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='gym.trainingsession', verbose_name='Sesiune antrenament')),
            ],
            options={
                'verbose_name': 'Check-in',
                'verbose_name_plural': 'Check-in-uri',
                'ordering': ['-timestamp'],
                'unique_together': {('athlete', 'training_session', 'timestamp')},
            },
        ),
    ]
