# Generated by Django 4.2.7 on 2026-01-05 13:14

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_athlete_phone_subscription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkin',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='checkin',
            name='checkin_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data check-in'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='athlete',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nume'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='phone_number',
            field=models.CharField(default=1, help_text='Format: 07XXXXXXXX (10 cifre)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Numărul de telefon trebuie să fie format din 10 cifre și să înceapă cu 07 (ex: 0712345678)', regex='^07\\d{8}$')], verbose_name='Număr de telefon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='athlete',
            name='subscription_active',
            field=models.BooleanField(default=False, verbose_name='Abonament lunar activ'),
        ),
        migrations.AddConstraint(
            model_name='checkin',
            constraint=models.UniqueConstraint(fields=('athlete', 'training_session', 'checkin_date'), name='unique_athlete_session_date'),
        ),
    ]
