# Generated by Django 4.2.7 on 2026-01-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_alter_checkin_unique_together_checkin_checkin_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='subscription_active',
            field=models.BooleanField(default=True, verbose_name='Abonament lunar activ'),
        ),
    ]
