# Generated by Django 4.2.7 on 2026-01-31 11:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_alter_athlete_subscription_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_cost', models.DecimalField(decimal_places=2, default=75.0, max_digits=10, verbose_name='Cost abonament lunar')),
                ('session_cost', models.DecimalField(decimal_places=2, default=20.0, max_digits=10, verbose_name='Cost per sesiune')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Setări aplicație',
                'verbose_name_plural': 'Setări aplicație',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Format: 07XXXXXXXX (10 cifre)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Numărul de telefon trebuie să fie format din 10 cifre și să înceapă cu 07 (ex: 0712345678)', regex='^07\\d{8}$')], verbose_name='Număr de telefon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Număr de telefon',
                'verbose_name_plural': 'Numere de telefon',
                'ordering': ['phone_number'],
            },
        ),
        migrations.AddField(
            model_name='athlete',
            name='pin',
            field=models.CharField(blank=True, help_text='PIN unic de 6 cifre pentru verificare', max_length=6, null=True, unique=True, verbose_name='PIN (6 cifre)'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Nu mai este folosit, doar pentru migrare', max_length=10, null=True, verbose_name='Număr de telefon (legacy)'),
        ),
        migrations.CreateModel(
            name='PhoneAthlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Data verificării PIN')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='gym.athlete', verbose_name='Sportiv')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletes', to='gym.phonenumber', verbose_name='Număr de telefon')),
            ],
            options={
                'verbose_name': 'Asociere telefon-sportiv',
                'verbose_name_plural': 'Asocieri telefon-sportiv',
                'ordering': ['phone_number', 'athlete'],
                'unique_together': {('phone_number', 'athlete')},
            },
        ),
        migrations.CreateModel(
            name='AthletePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='An')),
                ('month', models.IntegerField(verbose_name='Lună (1-12)')),
                ('paid', models.BooleanField(default=False, verbose_name='Plătit')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card')], max_length=10, null=True, verbose_name='Metoda de plată')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='gym.athlete', verbose_name='Sportiv')),
            ],
            options={
                'verbose_name': 'Plată sportiv',
                'verbose_name_plural': 'Plăți sportivi',
                'ordering': ['-year', '-month', 'athlete'],
                'unique_together': {('athlete', 'year', 'month')},
            },
        ),
    ]
