# Generated by Django 4.2.7 on 2026-01-31 11:26

from django.db import migrations
import random
import string


def generate_unique_pin(apps):
    """Generează un PIN unic de 6 cifre"""
    Athlete = apps.get_model('gym', 'Athlete')
    while True:
        pin = ''.join(random.choices(string.digits, k=6))
        if not Athlete.objects.filter(pin=pin).exists():
            return pin


def backfill_pins_and_phones(apps, schema_editor):
    """Backfill: generează PIN-uri și creează asocieri PhoneAthlete"""
    Athlete = apps.get_model('gym', 'Athlete')
    PhoneNumber = apps.get_model('gym', 'PhoneNumber')
    PhoneAthlete = apps.get_model('gym', 'PhoneAthlete')
    
    for athlete in Athlete.objects.all():
        # Generează PIN unic
        if not athlete.pin:
            athlete.pin = generate_unique_pin(apps)
            athlete.save()
        
        # Dacă atletul are phone_number legacy, creează PhoneNumber și PhoneAthlete
        if athlete.phone_number:
            phone_obj, created = PhoneNumber.objects.get_or_create(
                phone_number=athlete.phone_number
            )
            PhoneAthlete.objects.get_or_create(
                phone_number=phone_obj,
                athlete=athlete,
                defaults={'verified_at': athlete.created_at}  # Marchez ca verify pe data creării
            )


def reverse_backfill(apps, schema_editor):
    """Revert: șterge asocierile PhoneAthlete și PhoneNumber"""
    PhoneAthlete = apps.get_model('gym', 'PhoneAthlete')
    PhoneNumber = apps.get_model('gym', 'PhoneNumber')
    PhoneAthlete.objects.all().delete()
    PhoneNumber.objects.all().delete()
    
    # Ștergere PIN-uri
    Athlete = apps.get_model('gym', 'Athlete')
    for athlete in Athlete.objects.all():
        athlete.pin = None
        athlete.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_appsettings_phonenumber_athlete_pin_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_pins_and_phones, reverse_backfill),
    ]
