# Generated by Django 4.2.7 on 2026-02-01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_backfill_pins_and_phone_associations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ora check-in'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='checkin_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Data check-in'),
        ),
    ]
